### ISSUE TITLE
The game screen is cut off when redisplaying the window after minimizing it.

### ISSUE THREAD

**Issue by shunky1986** [ElectronicObserverEN/ElectronicObserver#417]
Thank you for deveropment and maintenance.
The game screen is cut off when redisplaying the window after minimizing it.

最小化後に再度表示させると、ゲーム画面が見切れてしまいます。

![reopen](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/152056715/92c3424e-4915-432a-a349-aba7ea227316)

**Comment by myangelkamikaze** [comment]
Which browser are you using?

![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/40002167/a4da2c5b-6290-4e57-8dd0-44e027858511)

Does the issue get fixed by restarting 七四式?
Are you using multiple screens?

**Comment by shunky1986** [comment]
I'm using CefSharp.
This problem didn't fix by restarting 七四式.
I'm not using multiple screens.

**Comment by myangelkamikaze** [comment]
https://github.com/ElectronicObserverEN/ElectronicObserver/issues/429#issuecomment-1873719521
